version: '2'

services:
  app:
    build:
      context: ./app
    ports:
      - 80:3000
    volumes:
      - ./app:/root/src

  server:
    build:
      context: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/root/src